default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "lavix" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "lavix" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  database: lavix_development

test:
  <<: *default
  database: lavix_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
